// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDs_Jjkj9VCYF7JR_LBKSuCr9-bmiODZE',
    appId: '1:777457931779:web:1d55bda9fc89ce36612036',
    messagingSenderId: '777457931779',
    projectId: 'carehealthapps',
    authDomain: 'carehealthapps.firebaseapp.com',
    storageBucket: 'carehealthapps.firebasestorage.app',
    measurementId: 'G-23Z0VLDGJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClO4U2X214ZXIAuv9qqiTpjvYICxVvbJs',
    appId: '1:777457931779:android:3c96447c7dbabb78612036',
    messagingSenderId: '777457931779',
    projectId: 'carehealthapps',
    storageBucket: 'carehealthapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5gjJVsctfIxca9tdPiYuq_Oh16-JhZk',
    appId: '1:777457931779:ios:2d16347b24d561cb612036',
    messagingSenderId: '777457931779',
    projectId: 'carehealthapps',
    storageBucket: 'carehealthapps.firebasestorage.app',
    iosBundleId: 'com.carehealthapps.carehealthapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5gjJVsctfIxca9tdPiYuq_Oh16-JhZk',
    appId: '1:777457931779:ios:2d16347b24d561cb612036',
    messagingSenderId: '777457931779',
    projectId: 'carehealthapps',
    storageBucket: 'carehealthapps.firebasestorage.app',
    iosBundleId: 'com.carehealthapps.carehealthapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDs_Jjkj9VCYF7JR_LBKSuCr9-bmiODZE',
    appId: '1:777457931779:web:3a4c2af3db0f269a612036',
    messagingSenderId: '777457931779',
    projectId: 'carehealthapps',
    authDomain: 'carehealthapps.firebaseapp.com',
    storageBucket: 'carehealthapps.firebasestorage.app',
    measurementId: 'G-BETW8MN8J8',
  );
}
